### ISSUE TITLE
pugjs.com cannot be reached

### ISSUE THREAD

**Issue by brianmhunt** [pugjs/pug-en#1]
> pugjs.com refused to connect.

Just a heads up.

**Comment by TimothyGu** [comment]
> It **_will**_ be live at https://pugjs.com.
> – [README](https://github.com/pugjs/pug-en#readme)

;)

**Comment by mk-pmb** [comment]
Nowadays the README says the URL is https://pugjs.org/ but there I get just the cloudflare captcha. In case you prefer to keep them ([why not](http://web.archive.org/web/20171024011347/http://cryto.net/~joepie91/blog/2016/07/14/cloudflare-we-have-a-problem/)), could you at least allow read access even to TOR users?
