### ISSUE TITLE
What does mean "written inline with attributes"?

### ISSUE THREAD

**Issue by kylekatarnls** [pugjs/pug-en#18]
Hi,

I did not understand what does mean "with attributes" regarding to buffered code?

https://github.com/pugjs/pug-en/blob/master/src/language/code.md#buffered-code

```It can also be written inline with attributes, and supports the full range of JavaScript expressions:```

I was asking myself if it could be a mistake since I do not see any attributes in the example.

Thanks,

**Comment by ForbesLindesay** [comment]
Could you review #19 and give me feedback if you think this could still be clearer.
