### ISSUE TITLE
Does pug v2 append file extension?

### ISSUE THREAD

**Issue by LionNatsu** [pugjs/pug-en#4]
https://github.com/pugjs/pug-en/blob/master/src/language/inheritance.md

> In Pug v1, if no file extension is given, .pug is automatically appended to the path, but in Pug v2 this is behavior is deprecated.

https://github.com/pugjs/pug-en/blob/master/src/language/includes.md

> In Pug v1, if no file extension is given, .pug is automatically appended to the file name, but in Pug v2 this is behavior is removed.

Are they behave differently? or is a typo?

(master is at efc8d8f5c59347d58427934695bfae9a0d36e18f, now)

**Comment by TimothyGu** [comment]
The latter is incorrect. Pull request welcome
